require: rubocop-rails

AllCops:
  Exclude:
    - db/schema.rb
    - Gemfile

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 50

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodLength:
  Max: 30
